name: helloGithubAction

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v2
    - name : 파일목록 출력
      run: ls -al
    - name : 파이썬 실행
      run: python test.py
